Updates application-release action

diff --git a/.github/workflows/application-release.yaml b/.github/workflows/application-release.yaml
--- a/.github/workflows/application-release.yaml
+++ b/.github/workflows/application-release.yaml
@@ -12,6 +12,17 @@ on:
       release-content:
         type: string
         required: true
+      release-package:
+        type: boolean
+        default: true
+      release-package-locations:
+        type: string
+        description: 'A comma-separated list of package locations'
+        required: true
+      release-package-build-locations:
+        type: string
+        description: 'A comma-separated list of package build locations'
+        required: true
     
 run-name: 'version set to ${{ inputs.release-version }} for release'
 
@@ -23,6 +34,14 @@ jobs:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
+
+    - name: Install NodeJS
+      uses: actions/setup-node@v4
+      with:
+        node-version: 18
+
+    - name: Install TypeScript compiler
+      run: npm i -g typescript
 
     - name: "Configure Git"
       run: |
@@ -38,6 +57,48 @@ jobs:
         docker buildx build --tag ${{ inputs.application-name }} -o type=image --platform=linux/arm64,linux/amd64 .
         docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
         docker buildx build --push --tag ghcr.io/codbex/${{ inputs.application-name }}:${{ inputs.release-version }} -o type=image --platform=linux/arm64,linux/amd64 .
+
+    - name: Update package.json version and Build TypeScript
+      if: ${{ inputs.release-package }}
+      run: |
+        IFS=',' read -r -a packages <<< "${{ inputs.release-package-locations }}"
+        for package in "${packages[@]}"; do
+          cd $package
+          npm version ${{ inputs.release-version }} --no-git-tag-version
+          git add package.json
+          cd ../
+        done
+
+        IFS=',' read -r -a buildLocations <<< "${{ inputs.release-package-build-locations }}"
+        for buildLocation in "${buildLocations[@]}"; do
+          cd $buildLocation
+          tsc --pretty > tsc-output.log 2>&1 || true
+          cd ../
+        done
+
+        for buildLocation in "${buildLocations[@]}"; do
+          cd $buildLocation
+          grep -v 'TS2688' tsc-output.log > filtered-tsc-output.log
+          cd ../
+        done
+
+        echo "Print Filtered Errors"
+
+        for buildLocation in "${buildLocations[@]}"; do
+        cd $buildLocation
+        cat filtered-tsc-output.log
+        cd ../
+        done
+
+        echo "Fail on Non-Ignored Errors"
+
+        for buildLocation in "${buildLocations[@]}"; do
+          cd $buildLocation
+          if grep -q 'error TS' filtered-tsc-output.log; then
+            exit 1
+          fi
+          cd ../
+        done
 
     - name: Git Push Release Branch
       run: |
